var config = {
  //all this data is generated by firebase. you just copy and paste
  apiKey: "AIzaSyCbjA9gq7rlhUz9Uw7X33s_-iR2lMDdV9M",
    authDomain: "personalwebsite-77fff.firebaseapp.com",
    databaseURL: "https://personalwebsite-77fff.firebaseio.com",
    projectId: "personalwebsite-77fff",
    storageBucket: "personalwebsite-77fff.appspot.com",
    messagingSenderId: "728888928642",
    appId: "1:728888928642:web:eaedaefba545f064a8479b",
    measurementId: "G-N9FPEM8NBX"
};
firebase.initializeApp(config);

var uploadStatus = document.getElementById("uploadStatus");
var fileButton = document.getElementById("fileUpload");
var messageStatus = document.getElementById("message2");

fileButton.addEventListener("change", function(e) {
  messageStatus.innerHTML = "Audio has been uploaded!";
  uploadStatus.value = 100;
  var file = e.target.files[0];
  var storageRef = firebase.storage().ref("audioFiles/"+file.name);
  var task = storageRef.put(file);


  task.on('state-changed',
    function progress(snapshot){
      var currentProgress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
      uploadStatus.value = currentProgress;
      uploadStatus.style.wid
    },
    function error(err) {
      messageStatus.innerHTML = "Your audio was not uploaded";

      console.log(err);
    },
    function complete() {

    });
});
